---
version: "3.5"

services:
  php74:
    build: ./php74
    volumes:
      - ./data/webroot/php74:/var/www/html
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8074:80

  php80:
    build: ./php80
    volumes:
      - ./data/webroot/php80:/var/www/html
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:80

  db57:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: verySecPasswoD
      MYSQL_DATABASE: db57
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    volumes:
      - ./data/db57:/var/lib/mysql

  db80:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: verySecPasswoD
      MYSQL_DATABASE: db80
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    volumes:
      - ./data/db80:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8000:8080
