---
version: "3.5"

services:

### APP containers
  php74:
    build: ./php74
    volumes:
      - ./webroot/php74:/var/www/html
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8074:80

  php80:
    build: ./php80
    volumes:
      - ./webroot/php80:/var/www/html
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:80

  php81:
    build: ./php81
    volumes:
      - ./webroot/php81:/var/www/html
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8081:80


### DB containers
  mysql57:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: verySecPasswoD
      MYSQL_DATABASE: newdb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    volumes:
      - ./db/dbmysql57:/var/lib/mysql

  mysql80:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: verySecPasswoD
      MYSQL_DATABASE: newdb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    volumes:
      - ./db/dbmysql80:/var/lib/mysql

  mariadb1010:
    image: mariadb:10.10
    restart: always
    ports:
      - 33306:3306
    environment:
      MARIADB_ROOT_PASSWORD: verySecPasswoD
      MARIADB_DATABASE: newdb
      MARIADB_USER: dbuser
      MARIADB_PASSWORD: dbpass
    volumes:
      - ./db/dbmariadb1010:/var/lib/mysql

  postgres15:
    image: postgres:15
    restart: always
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: verySecPasswoD
      PGDATA: /pgdata
    volumes:
      - ./db/dbpostgres15:/pgdata


### Adminer
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8000:8080
